import { Model, Types } from "mongoose";

export enum NOTIFICATION_TYPE {
  // Auth / User
  USER_REGISTERED = "USER_REGISTERED",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  PLAYER_PROFILE_CREATED = "PLAYER_PROFILE_CREATED",
  PLAYER_APPROVED = "PLAYER_APPROVED",
  PLAYER_REJECTED = "PLAYER_REJECTED",

  // Transfer
  TRANSFER_REQUESTED = "TRANSFER_REQUESTED",
  TRANSFER_APPROVED = "TRANSFER_APPROVED",
  TRANSFER_REJECTED = "TRANSFER_REJECTED",

  // Reward Order
  REWARD_ORDER_PLACED = "REWARD_ORDER_PLACED",
  REWARD_ORDER_APPROVED = "REWARD_ORDER_APPROVED",
  REWARD_ORDER_REJECTED = "REWARD_ORDER_REJECTED",
  REWARD_ORDER_DELIVERED = "REWARD_ORDER_DELIVERED",

  // Subscription
  SUBSCRIPTION_ACTIVATED = "SUBSCRIPTION_ACTIVATED",
  SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED",

  // Match & Team
  MATCH_REMINDER = "MATCH_REMINDER",
  MATCH_RESULT_PUBLISHED = "MATCH_RESULT_PUBLISHED",
  MATCH_RESULT = "MATCH_RESULT",
  MATCH_EVENT = "MATCH_EVENT",
  CLEAN_SHEET = "CLEAN_SHEET",
  TEAM_UPDATE = "TEAM_UPDATE",

  // News
  NEWS_PUBLISHED = "NEWS_PUBLISHED",

  // General
  GENERAL = "GENERAL",
}

export enum NOTIFICATION_CATEGORY {
  GENERAL_NEWS = "GENERAL_NEWS",
  TRANSFERS_GOSSIP = "TRANSFERS_GOSSIP",
  PLAYER_OF_THE_WEEK = "PLAYER_OF_THE_WEEK",
  MATCH_UPDATE = "MATCH_UPDATE",
}

export type INotification = {
  receiver: Types.ObjectId;   // কে পাবে (User _id)
  title: string;
  message: string;
  type: NOTIFICATION_TYPE;
  category: NOTIFICATION_CATEGORY;
  isRead: boolean;
  metadata?: Record<string, any>; // extra data (optional)
};

export type NotificationModel = Model<INotification>;