module.exports = {
  apps: [
    {
      name: 'eng-backend',
      script: 'dist/server.js',
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '3G',
      kill_timeout: 5000,
      wait_ready: false,
      listen_timeout: 10000,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
      error_file: 'logs/pm2-err.log',
      out_file: 'logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      log_type: 'json',
      env_production: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 5005,
      },
      source_map_support: true,
      instance_var: 'INSTANCE_ID',
      node_args: '--max-old-space-size=3072',
    },
  ],
}