
// System Role 

export enum USER_ROLES {
    ADMIN = 'ADMIN',
    SUPER_ADMIN = 'SUPER_ADMIN',
    PLAYER = 'PLAYER',
    MANAGER = 'MANAGER',
    OTHER_CLUBS = 'OTHER_CLUBS',
    REFEREE = 'REFEREE',
    TOURNAMENT_PLAYER = 'TOURNAMENT_PLAYER'
}

export const ROLE_GROUPS = {
    All: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN, USER_ROLES.PLAYER, USER_ROLES.MANAGER, USER_ROLES.OTHER_CLUBS, USER_ROLES.REFEREE, USER_ROLES.TOURNAMENT_PLAYER],
    MANAGEMENT: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN, USER_ROLES.MANAGER],
    PLAYER_MANAGEMENT: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN, USER_ROLES.PLAYER, USER_ROLES.MANAGER, USER_ROLES.OTHER_CLUBS],
    REFEREE_MANAGEMENT: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN, USER_ROLES.REFEREE],
    TOURNAMENT_MANAGEMENT: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN, USER_ROLES.PLAYER, USER_ROLES.MANAGER, USER_ROLES.OTHER_CLUBS, USER_ROLES.REFEREE, USER_ROLES.TOURNAMENT_PLAYER],
    ADMINS: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN]
}